version: '3'
services:
  freqtrade-dryrun:
    image: freqtradeorg/freqtrade:stable
    ports:
      - "8000:8080"
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
    container_name: freqtrade-dryrun
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.dryrun.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config.secrets.dryrun.json
      --strategy Strategy004
    networks:
      - default